x=int(input("Enter first number"))
y=int(input("Enter second number"))
print("Numbers before swapping")
print("First number-",x)
print("Second number-",y)
(x,y)=(y,x)
print("Numbers after swapping-")
print("First number-",x)
print("second number-",y)
