obj1=open("check.txt","r")
print(obj1.tell())
obj1.seek(3)
print(obj1.read())
obj1.seek(6)
print(obj1.read())
print("Current location of the pointer",obj1.tell())
obj1.seek(10)
print(obj1.read(5))
print("Current location of the pointer",obj1.tell())
obj1.close()
